theme: jekyll-theme-minimal
title: Easy ADB and fastboot (EAF)
description: 一個圖形化的ADB和fastboot工具
show_downloads: true
github:
  zip_url: https://github.com/ryantsui1109/Easy_ADB_fastboot/releases/latest/download/Easy.ADB.and.fastboot-win.zip
  tar_url: https://github.com/ryantsui1109/Easy_ADB_fastboot/releases/latest/download/easy_adb_fastboot-linux.tar.gz
  repository_url: https://github.com/ryantsui1109/Easy_ADB_fastboot
  repository_nwo: ryantsui1109/Easy_ADB_fastboot